import localFont from "next/font/local";
import "./globals.css";
import Navigation from "@/components/navigation";
import { createClient } from "@/prismicio";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const client = createClient();

  const settings = await client.getSingle("navigation");

  return (
    <html lang="en">

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <Navigation
        settings={settings} 
      />
        {children}
      </body>
    </html>
  );
}
